name: 'Terraform Deploy example infra to Azure'

on:
  push:
    branches:
      - main # or any other branch you want to deploy from 
      - '*'
  pull_request:
    branches:
      - main
  workflow_dispatch: # This enables manual triggers for the workflow

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: 
      name: ${{ github.ref == 'refs/heads/main' && 'prd' || 'dev' }}

    defaults:
      run:
        working-directory: infra/infra-example

    steps:
      - uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.7.x"
          terraform_wrapper: false

      - name: 'Terraform Init'
        run: |
          terraform init `
            -backend-config="resource_group_name=${{ vars.BACKEND_RG_NAME }}" `
            -backend-config="storage_account_name=${{ vars.BACKEND_ST_NAME }}" `
            -backend-config="container_name=${{ vars.BACKEND_CONTAINER_NAME }}" `
            -backend-config="key=${{ vars.BACKEND_KEY }}.tfstate"
        env:
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}

      - name: 'Terraform Validate'
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan  -var-file="vars/${{ vars.TF_VAR }}.tfvars" -out="terraform.tfplan"
        
        env:
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}

      - name: Upload Terraform Plan
        uses: actions/upload-artifact@v2
        with:
          name: tfplan
          path: .
  terraform_apply:
    needs: terraform
    runs-on: ubuntu-latest     
    environment:
      name: ${{ github.ref == 'refs/heads/main' && 'prd' || 'dev' }}
    defaults:
      run:
        working-directory: infra/infra-example

    steps:
      - uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.x
          terraform_wrapper: false

      - name: Download Terraform Plan
        uses: actions/download-artifact@v2
        with:
          name: tfplan
          path: .

      - name: Terraform Apply
        run: terraform apply -auto-approve ./terraform.tfplan
        env:
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
